# Global config.
title = "Sia"
baseurl = "http://sia.tech/" # TODO: https?
googleAnalytics = "UA-58715089-4"

# i18n and language specific config.
IsMultiLingual = true
DefaultContentLanguage = "en"
[Languages]
  [Languages.en]
    weight = 1
  [Languages.fr]
    weight = 2
  [Languages.ru]
    weight = 3
  [Languages.zh-hans]
    weight = 4
  [Languages.zh-hant]
    weight = 5
