# Global config.
title = "Sia"
baseurl = "http://sia.tech/" # TODO: https?

# i18n and language specific config.
IsMultiLingual = true
DefaultContentLanguage = "en"
[Languages]
  [Languages.en]
    weight = 1
  [Languages.fr]
    weight = 2
